# Basic
title: Cool Panda
subtitle: This is Yichang Wu's blog.
# welcome_message: Birds of a feather, flock together.
description: Do one thing, and do it well. 
creator: <a href="">Yichang Wu</a>

url: ''
# baseurl : '/cool-panda'
# baseurl : 'https://coolpanda.ml'

# permalink: /:year/:month/:title/
permalink: /:year-:month-:day/:title.html

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: blue

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog
    url: '/webs/index'
    # url: '/#c'

# Navigation buttons in the front page.
nav:
    - {title: List, description: List, url: '/webs/list'}
    - {title: About, description: About me, url: '/webs/about'}
    # - {title: Admin, description: Backend management system, url: '/admin'}
    # - {title: EBook 1, description: live and learn, url: 'https://albert-w.github.io/live-and-learn/'}
    # - {title: EBook 2, description: Exchristian, url: 'https://exchristian.github.io/'}
    # - {title: Tiny Tool, description: Fold Locker, url: 'https://albert-w.github.io/Folder-locker/'}

# Pagination
# gems: [jekyll-paginate]
plugins: [jekyll-paginate, jekyll-gist]
paginate: 5
paginate_path: "webs/page/:num/"
# paginate_path: "page/:num/"

# Comment
comment:
    # disqus: 
    # duoshuo: 
    
# Social
social:
    # weibo: 
    github: Albert-W
    # twitter: 
    # gplus: 
    # mail: 
    # zhihu: pfdlw

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host

exclude: ["xxx", "changelog.md", "nohup.out"]    

# compress the css file.
sass:
    style: compressed